---
name: publish-to-quay
on:
  push:
    branches-ignore:
    - '*'
    tags:
    - 'v[0-9]*'
jobs:
  build:
    if: github.repository == 'jkupferer/python-kopf-s2i'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Get the version
      id: get_version
      run: |
        VERSION=${GITHUB_REF#refs/tags/}
        echo ::set-output name=FULL_VERSION::${VERSION}
        echo ::set-output name=MINOR_VERSION::${VERSION%.*}
    - name: Publish My Image to Quay
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: jkupferer/python-kopf-s2i
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_PASSWORD }}
        registry: quay.io
        dockerfile: Dockerfile
        tags: ${{ steps.get_version.outputs.FULL_VERSION }},${{ steps.get_version.outputs.MINOR_VERSION }},latest
